loki:
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    persistence:
      storageClass: openebs-hostpath
      size: 1Gi
  loki:
    commonConfig:
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      lifecycler:
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      # max_transfer_retries: 0
      chunk_encoding: snappy
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3:
        s3: http://C9LqENA4K9HbwYO79U6y:sVHgwClMflLX2WDwcCWS7dMN6j6WvNQyQagerVdz@minio.minio
        # endpoint: http://minio.minio
        insecure: true
        s3ForcePathStyle: true
        # accessKeyId: C9LqENA4K9HbwYO79U6y
        # secretAccessKey: sVHgwClMflLX2WDwcCWS7dMN6j6WvNQyQagerVdz

  backend:
    replicas: 0
    # persistence:
    #   storageClass: mayastor-etcd-localpv
  read:
    replicas: 0
    # persistence:
    #   storageClass: mayastor-etcd-localpv
  write:
    replicas: 0
    # persistence:
    #   storageClass: mayastor-etcd-localpv
  minio:
    enabled: false
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
  gateway:
    enabled: false
  chunksCache:
    enabled: false
  memberlist:
    service:
      publishNotReadyAddresses: true
