version: '3'

networks:
  web:
    external:
      name: web
  # internal:
  #   external: false

services:
  moat:
    image: traefik:2.0-alpine
    command: --api --providers.docker
    networks:
      - web
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./rules.toml:/rules.toml
      - ./logs/:/logs/
      - ./acme/:/acme/
    restart: always
  tower:
    image: tower
    networks:
      - web
    labels:
      - 'traefik.HTTP.Routers.Tower.rule=Host(`tower.quaternion.media`)'
