version: '3'

networks:
  web:
    external:
      name: web

services:
  moat:
    image: traefik:v2.4
    command: 
      - --api.insecure=true
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https


      - "--certificatesresolvers.le.acme.email=junk@harpo.me"
      - "--certificatesresolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - --log.filePath=/logs/a.log
      - --log.level=DEBUG
      - --providers.file.directory=/config
      - --providers.file.watch=true
    networks:
      - web
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/:/logs/
      - ./acme/:/acme/
      - ./rules.yml:/config/rules.yml
    restart: always

  tower:
    image: tower
    build: tower
    networks:
      - web
    labels:
      - traefik.http.routers.Tower.rule=Host(`tower.quaternion.media`)
#      - traefik.http.routers.Tower.entrypoints=websecure
#      - traefik.http.routers.Tower.tls=true
#      - traefik.http.routers.Tower.tls.certresolver=le
