version: '3'

networks:
  web:
    external:
      name: web

services:
  moat:
    image: traefik:v2.0.0-alpha4-alpine
    command:
      --api 
      --providers.docker
    networks:
      - web
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
        #    labels:
        #      - "traefik.http.middlewares.redirect.Headers.SSLRedirect=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./rules.toml:/etc/traefik/rules.toml
      - ./logs/:/logs/
      - ./acme/:/acme/
    restart: always
  tower:
    image: tower
    networks:
      - web
    labels:
      - 'traefik.HTTP.Routers.Tower.rule=Host(`tower.quaternion.media`)'
