#!/bin/bash

if [ $1 = "dev" ] || [ -z $1 ]; then
if [ !-z ]; then shift; fi

echo "moat running dev $1"
#docker-compose -f docker-compose.yml -f dev.yml up $1
docker-compose up

elif [ $1 = "prod" -o $1 = "production" ]; then
shift
echo "moat running production $1"
docker-compose down && \
docker-compose -f docker-compose.yml -f production.yml up --build -d $1

elif [ $1 = "i" -o $1 = "install" ]; then
  shift
  echo "moat configuring"
  docker network create web

fi
