[Global]
Debug = true

#[EntryPoints]
#  [EntryPoints.http]
#    Address = ":80"
#  [EntryPoints.https]
#    Address = ":443"
#  [EntryPoints.adminPortal]
#    Address = ':8080'

[acme]
Email = 'harpo@harpo.me'
Storage = '/acme/acme.json'
OnHostRule = true
  [acme.tlschallenge]
    EntryPoint = "http"

