# traefik.toml


# Set up logging.
[log]
filePath = "/logs/traefik.log"
level = 'debug'

[accessLog]
filePath = '/logs/access.log'
# accessLogsFile = "/logs/access.log"

# Set the Web Admin Port.
#[web]
#address = ":8080"

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"
#  [entrypoints.admin]
#    address = ":8080"

# Configure Traefik to watch a file for config changes.
[providers]
  [providers.file]
    Directory = '/etc/traefik'
    filename = "rules.toml"
    watch = true
