
[log]
filePath = "/logs/traefik.log"
level = 'info'

[accessLog]
filePath = '/logs/access.log'

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

[http.middlewares]
  [http.middlewares.redirect.headers]
    SSLRedirect = true
#    SSLForceHost = true

[acme]
  Email = 'harpo@harpo.me'
  Storage = '/acme/acme.json'
  OnHostRule = true
  ACMELogging = true
  [acme.httpchallenge]
    EntryPoint = "http"
#  [acme.tlschallenge]

[providers]
  [providers.file]
    Directory = '/etc/traefik'
    Filename = "rules.toml"
    Watch = true
