
[log]
filePath = "/logs/traefik.log"
level = 'error'

[entrypoints]
  [entrypoints.web]
    address = ":80"

  [entrypoints.websecure]
    address = ":443"


[certificatesResolvers.sample.acme]
  email = "your-email@your-domain.org"
  storage = "acme.json"
  [certificatesResolvers.letsecrypt.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
