prometheus:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  server:
    persistentVolume:
      # storageClass: mayastor-etcd-localpv
      storageClass: openebs-hostpath
    extraArgs:
      web.enable-remote-write-receiver: ""
  alertmanager:
    enabled: false
