traefik:
  deployment:
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics
      prometheus.io/port: '9100'

  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: true

  logs:
    access:
      enabled: true
      format: json
      fields:
        headers:
          defaultmode: keep
    general:
      level: DEBUG

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    websecure:
      allowACMEByPass: true
  #     forwardedHeaders:
  #       trustedIPs:
  #       - 10.0.32.0/24
  #     proxyProtocol:
  #       trustedIPs:
  #       - 10.0.0.0/16
    
  service:
    spec:
      externalTrafficPolicy: Local

  metrics:
    addInternals: true
    prometheus:
      addRoutersLabels: true
      headerLabels:
        useragent: request_User-Agent
        ip: request_X-Real-Ip
      
  tracing:
    addInternals: true
    serviceName: traefik
    
    otlp:
      # enabled: true
      grpc:
        enabled: true
        endpoint: tempo.tempo:4317
        insecure: true

  providers:
    kubernetesIngress:
      allowExternalNameServices: true
    kubernetesCRD:
      allowExternalNameServices: true
