traefik:
  deployment:
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics
      prometheus.io/port: '9100'

  ingressClass:
    enabled: true
    isDefaultClass: true

  ingressRoute:
    dashboard:
      enabled: true

  logs:
    access:
      enabled: true
      format: json
      # filePath: /var/log/access.log
      fields:
        headers:
          defaultmode: keep
    general:
      level: DEBUG

  # additionalArguments:
  # - --log.filepath=/var/log/traefik/traefik.log
  # - --accesslog.filepath=/var/log/traefik/access.log

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    websecure:
      allowACMEByPass: true
  #     forwardedHeaders:
  #       trustedIPs:
  #       - 10.0.32.0/24
  #     proxyProtocol:
  #       trustedIPs:
  #       - 10.0.0.0/16
  #     tls:
  #       certResolver: production
  #       enabled: true
  #     middlewares:
  #       - traefik-bouncer@kubernetescrd
  #       # - traefik-captcha-protect@kubernetescrd
    
  service:
    spec:
      externalTrafficPolicy: Local

  # securityContext:
  #   readOnlyRootFilesystem: False
  #   runAsGroup: 0
  #   runAsUser: 0
  #   runAsNonRoot: false

  metrics:
    addInternals: true
    prometheus:
      addRoutersLabels: true
      headerLabels:
        # host: X-Forwarded-Host
        # host: ClientHost
        useragent: request_User-Agent
        ip: request_X-Real-Ip
    influxdb2:
      address: http://influxdb-influxdb2.influxdb
      token: wL6HxTgfL3mQIuT9i3FY4AasE4iZ-eshcDZGq-qb8k570dnm-bP9u8Ounnc7W5ZRg-PKbIyS3RCFNwROGpz5Fg==
      bucket: traefik
      org: 9e7602b64564cbef
      addRoutersLabels: true
    otlp:
      enabled: true
      addRoutersLabels: true
      http:
        endpoint: http://loki-backend.loki:3100/otlp/api/v1/logs

  # experimental:
  #   plugins:
  #     bouncer:
  #       moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
  #       version: v1.4.1
  #     captcha-protect:
  #       moduleName: github.com/libops/captcha-protect
  #       version: v1.0.0

  providers:
    kubernetesIngress:
      allowExternalNameServices: true
    kubernetesCRD:
      allowExternalNameServices: true