apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: harpo@harpo.me
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-west-1
          accessKeyIDSecretRef:
            name: route53-access-key
            key: access-key
          secretAccessKeySecretRef:
            name: route53-access-key
            key: secret-access-key
