grafana:
  persistence:
    enabled: true
    type: pvc
    size: 1Gi
  initChownData:
    enabled: false
  grafana.ini:
    server:
      root_url: https://graphs.harpo.me
      auth:
        signout_redirect_url: https://auth.harpo.me/application/o/grafana/end-session/
        oauth_auto_login: true
