apiVersion: v2
name: monitoring
description: A Helm chart for Grafana monitoring
version: 0.2.0
appVersion: 13.0.1
dependencies:
- name: grafana
  repository: oci://ghcr.io/grafana-community/helm-charts
  version: 12.3.0
- name: prometheus
  repository: oci://ghcr.io/prometheus-community/charts
  version: 29.5.0
