apiVersion: v2
name: metrics-server
description: A metrics server for Kubernetes
version: 0.0.1
dependencies:
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server
