apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groot
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/quaternionmedia/moat.git
    path: groot
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: groot
  syncPolicy:
    automated:
      selfHeal: true
