apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/quaternionmedia/moat.git
    path: openebs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    createNamespace: true
