argo-cd:
  global:
    addPrometheusAnnotations: true
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8083'
      prometheus.io/path: /metrics
  dex:
    enabled: false
  notifications:
    enabled: false  
  server:
    extraArgs:
      - --insecure
  configs:
    cm:
      kustomize.buildOptions: --enable-helm
