argo-cd:
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hostname: cd.harpo.me
      extraTls:
      - hosts:
        - cd.harpo.me
        secretName: argocd-server-tls-production
  configs:
    repositories:
      moat-git:
        name: moat-git
        url: git@github.com:quaternionmedia/moat.git
        # type: git
    credentialTemplates:
      moat-git-ssh:
        url: git@github.com
