apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.5
      # helm:
      #   valueFiles:
      #     - $values/argo-cd/helm/values.yml
    # - ref: values
    #   targetRevision: HEAD
    #   repoURL: https://github.com/quaternionmedia/moat.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
