akri:
  udev:
    discovery:
      enabled: true
    configuration:
      enabled: true
      discoveryDetails:
        groupRecursive: true
        udevRules:
        - KERNEL=="video[0-9]*", SUBSYSTEM=="video4linux", ENV{ID_V4L_CAPABILITIES}==":capture:"
        - KERNEL=="ttyUSB*"
  onvif:
    configuration:
      enabled: true
