akri:
  udev:
    discovery:
      enabled: true
    configuration:
      enabled: true
      # brokerPod:
      #   image:
      #     repository: ghcr.io/project-akri/akri/udev-video-broker
      #     tag: latest
      #     pullPolicy: IfNotPresent
      discoveryDetails:
        # groupRecursive: true
        udevRules:
        - KERNEL=="video[0-9]*", SUBSYSTEM=="video4linux", ENV{ID_V4L_CAPABILITIES}==":capture:"
        - KERNEL=="ttyUSB*"
