apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
data:
  go2rtc.yaml: |

    webrtc:
      listen: :8555
    api:
      listen: :1984
    rtmp:
      enabled: true
      listen: :1935
    rtsp:
      listen: :8554

    streams:
      HOffice: null
      Laboratory: null
