apiVersion: v2
name: csi
version: 0.1.5
appVersion: v0.18.1
description: Proxmox CSI Driver for Kubernetes
home: https://github.com/quaternionmedia/moat
dependencies:
- name: proxmox-csi-plugin
  version: 0.5.7
  repository: oci://ghcr.io/sergelogvinov/charts
